### ISSUE TITLE
Etag should use base64

### ISSUE THREAD

**Issue by hengfeiyang** [SeriousBug/actix-web-rust-embed-responder#5]
for now the Etag like this:

```
etag: "9#Mx17fRdIB3Ir7@y{bH>V(HN<k?bg$(!sI&=5--"
```

it should use base64 encode. i saw the file `rust_embed.rs` Etag used base64 encode.

Should we use base64 encode for `rust_embed_for_web.rs`?

Thanks

**Comment by SeriousBug** [comment]
`rust_embed_for_web` uses base85 encoding for the ETags. This is deliberate, base85 encoded tags are slightly shorter than base64, which saves some space on each request. `rust_embed_for_web` computes the encoded ETag header at compile time, so there is no performance impact to using base85 either. I don't think it makes sense to switch it to base64.

In fact, it might make sense to use base85 for `rust_embed` too. I avoided doing that because I was worried that it might impact performance, in case our base85 encoder is not as efficient as base64. But I haven't measured that in any way.

**Comment by hengfeiyang** [comment]
Thanks
